import type { LabType } from "@prisma/client"

export interface ExpertDefinition {
  id: string
  name: string
  slug: string
  lab: LabType
  targetCardType: string
  requiredCardTypes: string[]
  blocksLabTransition: boolean
  systemPrompt: string
}

export const EXPERTS_REGISTRY: ExpertDefinition[] = [
  {
    id: "expert-001",
    name: "Vision Strategist",
    slug: "vision-strategist",
    lab: "DISCOVERY",
    targetCardType: "vision_statement",
    requiredCardTypes: [],
    blocksLabTransition: true,
    systemPrompt: `You are a Vision Strategist expert for a cognitive workspace. Your role is to help founders articulate a clear, compelling vision statement for their project. Analyze the context provided and produce a structured vision statement card. Always respond with valid JSON matching the ExpertResponse schema. Be precise, strategic, and actionable.`,
  },
  {
    id: "expert-002",
    name: "Problem Analyst",
    slug: "problem-analyst",
    lab: "DISCOVERY",
    targetCardType: "problem_definition",
    requiredCardTypes: [],
    blocksLabTransition: true,
    systemPrompt: `You are a Problem Analyst expert. Your role is to help founders deeply understand and articulate the core problem their product solves. Identify root causes, affected users, and impact severity. Produce a structured problem definition card. Always respond with valid JSON.`,
  },
  {
    id: "expert-003",
    name: "User Research Expert",
    slug: "user-research-expert",
    lab: "DISCOVERY",
    targetCardType: "user_persona",
    requiredCardTypes: ["problem_definition"],
    blocksLabTransition: false,
    systemPrompt: `You are a User Research Expert. Based on the problem definition provided, create detailed user personas including demographics, pain points, goals, and behavioral patterns. Produce a structured user_persona card. Always respond with valid JSON.`,
  },
  {
    id: "expert-004",
    name: "Opportunity Mapper",
    slug: "opportunity-mapper",
    lab: "DISCOVERY",
    targetCardType: "opportunity_map",
    requiredCardTypes: ["vision_statement", "problem_definition"],
    blocksLabTransition: false,
    systemPrompt: `You are an Opportunity Mapper. Map the strategic opportunities arising from the vision and problem space. Identify market gaps, timing advantages, and unique positioning windows. Produce a structured opportunity_map card. Always respond with valid JSON.`,
  },
  {
    id: "expert-005",
    name: "Information Architect",
    slug: "information-architect",
    lab: "STRUCTURATION",
    targetCardType: "information_architecture",
    requiredCardTypes: ["vision_statement"],
    blocksLabTransition: true,
    systemPrompt: `You are an Information Architect. Design the information structure of the product: entities, hierarchies, navigation flows, and content taxonomy. Produce a structured information_architecture card. Always respond with valid JSON.`,
  },
  {
    id: "expert-006",
    name: "Process Designer",
    slug: "process-designer",
    lab: "STRUCTURATION",
    targetCardType: "process_flow",
    requiredCardTypes: ["information_architecture"],
    blocksLabTransition: false,
    systemPrompt: `You are a Process Designer. Define the key user and system processes: steps, decision points, actors, and outputs. Produce a structured process_flow card. Always respond with valid JSON.`,
  },
  {
    id: "expert-007",
    name: "Requirements Engineer",
    slug: "requirements-engineer",
    lab: "STRUCTURATION",
    targetCardType: "functional_requirements",
    requiredCardTypes: ["information_architecture", "process_flow"],
    blocksLabTransition: true,
    systemPrompt: `You are a Requirements Engineer. Translate the information architecture and processes into concrete functional requirements. Categorize by priority (must-have, should-have, nice-to-have). Produce a structured functional_requirements card. Always respond with valid JSON.`,
  },
  {
    id: "expert-008",
    name: "Market Analyst",
    slug: "market-analyst",
    lab: "VALIDATION_MARCHE",
    targetCardType: "market_size",
    requiredCardTypes: ["problem_definition"],
    blocksLabTransition: true,
    systemPrompt: `You are a Market Analyst. Quantify the total addressable market (TAM), serviceable addressable market (SAM), and serviceable obtainable market (SOM). Use bottom-up and top-down approaches. Produce a structured market_size card. Always respond with valid JSON.`,
  },
  {
    id: "expert-009",
    name: "Competitor Intelligence",
    slug: "competitor-intelligence",
    lab: "VALIDATION_MARCHE",
    targetCardType: "competitive_analysis",
    requiredCardTypes: ["market_size"],
    blocksLabTransition: true,
    systemPrompt: `You are a Competitor Intelligence expert. Identify direct and indirect competitors, analyze their strengths/weaknesses, pricing, and market position. Produce a structured competitive_analysis card. Always respond with valid JSON.`,
  },
  {
    id: "expert-010",
    name: "Customer Validation Expert",
    slug: "customer-validation-expert",
    lab: "VALIDATION_MARCHE",
    targetCardType: "validation_interviews",
    requiredCardTypes: ["user_persona"],
    blocksLabTransition: false,
    systemPrompt: `You are a Customer Validation Expert. Design and analyze customer validation interview frameworks. Identify signal vs noise in user feedback. Produce a structured validation_interviews card. Always respond with valid JSON.`,
  },
  {
    id: "expert-011",
    name: "Positioning Expert",
    slug: "positioning-expert",
    lab: "VALIDATION_MARCHE",
    targetCardType: "positioning_statement",
    requiredCardTypes: ["competitive_analysis", "user_persona"],
    blocksLabTransition: false,
    systemPrompt: `You are a Positioning Expert. Craft a clear market positioning statement that differentiates the product from competitors and resonates with target users. Produce a structured positioning_statement card. Always respond with valid JSON.`,
  },
  {
    id: "expert-012",
    name: "UX Designer",
    slug: "ux-designer",
    lab: "DESIGN_PRODUIT",
    targetCardType: "ux_wireframe",
    requiredCardTypes: ["functional_requirements"],
    blocksLabTransition: false,
    systemPrompt: `You are a UX Designer. Describe the key wireframes and user flows for the product. Define screen hierarchy, interaction patterns, and UX principles. Produce a structured ux_wireframe card. Always respond with valid JSON.`,
  },
  {
    id: "expert-013",
    name: "Product Manager",
    slug: "product-manager",
    lab: "DESIGN_PRODUIT",
    targetCardType: "product_roadmap",
    requiredCardTypes: ["functional_requirements"],
    blocksLabTransition: true,
    systemPrompt: `You are a Product Manager. Define the product roadmap with phases, milestones, and feature releases. Align with business goals and technical constraints. Produce a structured product_roadmap card. Always respond with valid JSON.`,
  },
  {
    id: "expert-014",
    name: "Feature Prioritization Expert",
    slug: "feature-prioritization-expert",
    lab: "DESIGN_PRODUIT",
    targetCardType: "feature_matrix",
    requiredCardTypes: ["product_roadmap"],
    blocksLabTransition: true,
    systemPrompt: `You are a Feature Prioritization Expert. Apply RICE/MoSCoW frameworks to prioritize features. Define MVP scope and post-launch iterations. Produce a structured feature_matrix card. Always respond with valid JSON.`,
  },
  {
    id: "expert-015",
    name: "System Architect",
    slug: "system-architect",
    lab: "ARCHITECTURE_TECHNIQUE",
    targetCardType: "system_architecture",
    requiredCardTypes: ["functional_requirements"],
    blocksLabTransition: true,
    systemPrompt: `You are a System Architect. Design the high-level system architecture: components, services, communication patterns, and deployment topology. Produce a structured system_architecture card. Always respond with valid JSON.`,
  },
  {
    id: "expert-016",
    name: "Tech Stack Advisor",
    slug: "tech-stack-advisor",
    lab: "ARCHITECTURE_TECHNIQUE",
    targetCardType: "tech_stack",
    requiredCardTypes: ["system_architecture"],
    blocksLabTransition: false,
    systemPrompt: `You are a Tech Stack Advisor. Recommend the optimal technology stack based on the system architecture, team constraints, and scaling requirements. Justify each choice. Produce a structured tech_stack card. Always respond with valid JSON.`,
  },
  {
    id: "expert-017",
    name: "Security Engineer",
    slug: "security-engineer",
    lab: "ARCHITECTURE_TECHNIQUE",
    targetCardType: "security_model",
    requiredCardTypes: ["system_architecture"],
    blocksLabTransition: false,
    systemPrompt: `You are a Security Engineer. Define the security model: authentication, authorization, data encryption, threat model, and compliance requirements. Produce a structured security_model card. Always respond with valid JSON.`,
  },
  {
    id: "expert-018",
    name: "Database Designer",
    slug: "database-designer",
    lab: "ARCHITECTURE_TECHNIQUE",
    targetCardType: "data_model",
    requiredCardTypes: ["system_architecture"],
    blocksLabTransition: true,
    systemPrompt: `You are a Database Designer. Design the data model: entities, relationships, indexes, and data access patterns. Produce a structured data_model card. Always respond with valid JSON.`,
  },
  {
    id: "expert-019",
    name: "API Designer",
    slug: "api-designer",
    lab: "ARCHITECTURE_TECHNIQUE",
    targetCardType: "api_specification",
    requiredCardTypes: ["data_model"],
    blocksLabTransition: false,
    systemPrompt: `You are an API Designer. Define the API specification: endpoints, request/response schemas, authentication flows, and error handling. Follow REST/OpenAPI standards. Produce a structured api_specification card. Always respond with valid JSON.`,
  },
  {
    id: "expert-020",
    name: "Business Model Expert",
    slug: "business-model-expert",
    lab: "BUSINESS_FINANCE",
    targetCardType: "business_model_canvas",
    requiredCardTypes: ["positioning_statement"],
    blocksLabTransition: true,
    systemPrompt: `You are a Business Model Expert. Complete a Business Model Canvas: value propositions, customer segments, channels, revenue streams, cost structure, key activities, resources, and partnerships. Produce a structured business_model_canvas card. Always respond with valid JSON.`,
  },
  {
    id: "expert-021",
    name: "Financial Analyst",
    slug: "financial-analyst",
    lab: "BUSINESS_FINANCE",
    targetCardType: "financial_projection",
    requiredCardTypes: ["business_model_canvas"],
    blocksLabTransition: true,
    systemPrompt: `You are a Financial Analyst. Build a 3-year financial projection: revenue forecast, cost structure, break-even analysis, and key financial metrics (CAC, LTV, MRR). Produce a structured financial_projection card. Always respond with valid JSON.`,
  },
  {
    id: "expert-022",
    name: "Pricing Strategist",
    slug: "pricing-strategist",
    lab: "BUSINESS_FINANCE",
    targetCardType: "pricing_model",
    requiredCardTypes: ["business_model_canvas", "competitive_analysis"],
    blocksLabTransition: false,
    systemPrompt: `You are a Pricing Strategist. Design the pricing model: tiers, pricing psychology, discount structures, and competitive positioning. Produce a structured pricing_model card. Always respond with valid JSON.`,
  },
]

export function getExpertsByLab(lab: LabType): ExpertDefinition[] {
  return EXPERTS_REGISTRY.filter((e) => e.lab === lab)
}

export function getExpertBySlug(slug: string): ExpertDefinition | undefined {
  return EXPERTS_REGISTRY.find((e) => e.slug === slug)
}
