import { z } from "zod";
import { StorySchema, QuotePropsSchema, AnnouncementPropsSchema, ChecklistPropsSchema } from "../schema/types";

/**
 * Partial schema for AI concepts (templateId + props).
 * We validate this before converting to a full StoryPayload.
 */
export const ConceptSchema = z.object({
    templateId: z.enum(["quote", "announcement", "checklist"]),
    props: z.any(), // Will be validated specifically based on templateId
});

export type StoryConcept = z.infer<typeof ConceptSchema>;

/**
 * Validates a single concept generated by the AI.
 */
export function validateConcept(concept: unknown): { success: true; data: StoryConcept } | { success: false; error: string } {
    const parse = ConceptSchema.safeParse(concept);
    if (!parse.success) {
        return { success: false, error: parse.error.message };
    }

    const { templateId, props } = parse.data;

    // Deep validate props based on templateId
    let propValidation;
    switch (templateId) {
        case "quote":
            propValidation = QuotePropsSchema.safeParse(props);
            break;
        case "announcement":
            propValidation = AnnouncementPropsSchema.safeParse(props);
            break;
        case "checklist":
            propValidation = ChecklistPropsSchema.safeParse(props);
            break;
        default:
            return { success: false, error: `Invalid templateId: ${templateId}` };
    }

    if (!propValidation.success) {
        return { success: false, error: propValidation.error.message };
    }

    return { success: true, data: { templateId, props: propValidation.data } };
}

/**
 * Filters and validates a list of concepts.
 */
export function validateConcepts(concepts: unknown[]): StoryConcept[] {
    return concepts
        .map(c => validateConcept(c))
        .filter(r => r.success)
        .map(r => (r as { success: true; data: StoryConcept }).data);
}
